name: CaptureTheWool
main: com.gmail.lynx7478.ctw.CTW
author: Raira
description: Capture the wool minigame plugin.
version: 3.0
commands:
   team:
     description: Joins a team.
   ctw:
     description: CTW main command.
   roles:
     description: Role command.
   afk:
     description: AFK command.